CREATE TABLE [dbo].[Role](
       [RoleId] UNIQUEIDENTIFIER NOT NULL,
       [Name] NVARCHAR(200) NULL,
	     [Status] INT NULL,
	     [Description] NVARCHAR(1000) NULL,
	     [CreatedOn] DATETIME NULL,
       [CreatedBy] UNIQUEIDENTIFIER NULL,
       [ModifiedOn] DATETIME NULL,
       [ModifiedBy] UNIQUEIDENTIFIER NULL,
PRIMARY KEY CLUSTERED 
(
       [RoleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
