CREATE TABLE [dbo].[RoleAccess](
       [RoleAccessId] UNIQUEIDENTIFIER NOT NULL,
	     [RoleId] UNIQUEIDENTIFIER NOT NULL,
	     [AccessId] UNIQUEIDENTIFIER NOT NULL,   
	     [CreatedOn] DATETIME NULL,
       [CreatedBy] UNIQUEIDENTIFIER NULL,
       [ModifiedOn] DATETIME NULL,
       [ModifiedBy] UNIQUEIDENTIFIER NULL,
PRIMARY KEY CLUSTERED 
(
       [RoleAccessId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
