CREATE TABLE [dbo].[UserRole](
       [UserRoleId] UNIQUEIDENTIFIER NOT NULL,
	     [UserId] UNIQUEIDENTIFIER NOT NULL,
	     [RoleId] UNIQUEIDENTIFIER NOT NULL,   
	     [CreatedOn] DATETIME NULL,
       [CreatedBy] UNIQUEIDENTIFIER NULL,
       [ModifiedOn] DATETIME NULL,
       [ModifiedBy] UNIQUEIDENTIFIER NULL,
PRIMARY KEY CLUSTERED 
(
       [UserRoleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
